target = "draft-ietf-plants-merkle-tree-certs.txt#appendix-A"

# ASN.1 Module
#
#    MerkleTreeCertificates
#      { iso(1) identified-organization(3) dod(6) internet(1)
#        security(5) mechanisms(5) pkix(7) id-mod(0)
#        id-mod-mtc-2025(TBD) }
# 
#    DEFINITIONS IMPLICIT TAGS ::=
#    BEGIN
# 
#    IMPORTS
#      SIGNATURE-ALGORITHM, AlgorithmIdentifier{},
#      FROM AlgorithmInformation-2009 -- in [RFC5912]
#        { iso(1) identified-organization(3) dod(6) internet(1)
#          security(5) mechanisms(5) pkix(7) id-mod(0)
#          id-mod-algorithmInformation-02(58) }
#      Extensions{}, ATTRIBUTE
#      FROM PKIX-CommonTypes-2009 -- in [RFC5912]
#        { iso(1) identified-organization(3) dod(6) internet(1)
#          security(5) mechanisms(5) pkix(7) id-mod(0)
#          id-mod-pkixCommon-02(57) }
#      CertExtensions
#      FROM PKIX1Implicit-2009 -- in [RFC5912]
#        { iso(1) identified-organization(3) dod(6) internet(1)
#          security(5) mechanisms(5) pkix(7) id-mod(0)
#          id-mod-pkix1-implicit-02(59) }
#      Version, Name, Validity, UniqueIdentifier, PublicKeyAlgorithms
#      FROM PKIX1Explicit-2009 -- in [RFC5912]
#        { iso(1) identified-organization(3) dod(6) internet(1)
#          security(5) mechanisms(5) pkix(7) id-mod(0)
#          id-mod-pkix1-explicit-02(51) }
#      TrustAnchorID
#      FROM TrustAnchorIDs-2025 -- in [I-D.ietf-tls-trust-ancohor-ids]
#        { iso(1) identified-organization(3) dod(6) internet(1)
#          security(5) mechanisms(5) pkix(7) id-mod(0)
#          id-mod-trustAnchorIDs-2025(TBD) } ;
# 
#    TBSCertificateLogEntry ::= SEQUENCE {
#        version               [0] EXPLICIT Version DEFAULT v1,
#        issuer                    Name,
#        validity                  Validity,
#        subject                   Name,
#        subjectPublicKeyAlgorithm AlgorithmIdentifier{PUBLIC-KEY,
#                                      {PublicKeyAlgorithms}},
#        subjectPublicKeyInfoHash  OCTET STRING,
#        issuerUniqueID        [1] IMPLICIT UniqueIdentifier OPTIONAL,
#        subjectUniqueID       [2] IMPLICIT UniqueIdentifier OPTIONAL,
#        extensions            [3] EXPLICIT Extensions{{CertExtensions}}
#                                               OPTIONAL
#    }
#    id-alg-mtcProof OBJECT IDENTIFIER ::= {
#        iso(1) identified-organization(3) dod(6) internet(1) security(5)
#        mechanisms(5) pkix(7) algorithms(6) TBD }
# 
#    sa-mtcProof SIGNATURE-ALGORITHM ::= {
#        IDENTIFIER id-alg-mtcProof
#        PARAMS ARE absent
#    }
# 
#    id-rdna-trustAnchorID OBJECT IDENTIFIER ::= {
#        iso(1) identified-organization(3) dod(6) internet(1) security(5)
#        mechanisms(5) pkix(7) rdna(25) TBD }
# 
#    at-trustAnchorID ATTRIBUTE ::= {
#        TYPE TrustAnchorID
#        IDENTIFIED BY id-rdna-trustAnchorID
#    }
# 
#    END

[[spec]]
level = "MAY"
quote = '''
TBSCertificateLogEntry ::= SEQUENCE {
version               [0] EXPLICIT Version DEFAULT v1,
issuer                    Name,
validity                  Validity,
subject                   Name,
subjectPublicKeyAlgorithm AlgorithmIdentifier{PUBLIC-KEY,
{PublicKeyAlgorithms}},
subjectPublicKeyInfoHash  OCTET STRING,
issuerUniqueID        [1] IMPLICIT UniqueIdentifier OPTIONAL,
subjectUniqueID       [2] IMPLICIT UniqueIdentifier OPTIONAL,
extensions            [3] EXPLICIT Extensions{{CertExtensions}}
OPTIONAL
}
id-alg-mtcProof OBJECT IDENTIFIER ::= {
iso(1) identified-organization(3) dod(6) internet(1) security(5)
mechanisms(5) pkix(7) algorithms(6) TBD }
'''

[[spec]]
level = "MAY"
quote = '''
TBSCertificateLogEntry ::= SEQUENCE {
version               [0] EXPLICIT Version DEFAULT v1,
issuer                    Name,
validity                  Validity,
subject                   Name,
subjectPublicKeyAlgorithm AlgorithmIdentifier{PUBLIC-KEY,
{PublicKeyAlgorithms}},
subjectPublicKeyInfoHash  OCTET STRING,
issuerUniqueID        [1] IMPLICIT UniqueIdentifier OPTIONAL,
subjectUniqueID       [2] IMPLICIT UniqueIdentifier OPTIONAL,
extensions            [3] EXPLICIT Extensions{{CertExtensions}}
OPTIONAL
}
id-alg-mtcProof OBJECT IDENTIFIER ::= {
iso(1) identified-organization(3) dod(6) internet(1) security(5)
mechanisms(5) pkix(7) algorithms(6) TBD }
'''

[[spec]]
level = "MAY"
quote = '''
TBSCertificateLogEntry ::= SEQUENCE {
version               [0] EXPLICIT Version DEFAULT v1,
issuer                    Name,
validity                  Validity,
subject                   Name,
subjectPublicKeyAlgorithm AlgorithmIdentifier{PUBLIC-KEY,
{PublicKeyAlgorithms}},
subjectPublicKeyInfoHash  OCTET STRING,
issuerUniqueID        [1] IMPLICIT UniqueIdentifier OPTIONAL,
subjectUniqueID       [2] IMPLICIT UniqueIdentifier OPTIONAL,
extensions            [3] EXPLICIT Extensions{{CertExtensions}}
OPTIONAL
}
id-alg-mtcProof OBJECT IDENTIFIER ::= {
iso(1) identified-organization(3) dod(6) internet(1) security(5)
mechanisms(5) pkix(7) algorithms(6) TBD }
'''

