target = "draft-ietf-plants-merkle-tree-certs.txt#section-9"

# ACME Extensions
#
#    This section describes how to issue Merkle Tree certificates using
#    ACME [RFC8555].
# 
#    When downloading the certificate (Section 7.4.2 of [RFC8555]), ACME
#    clients supporting Merkle Tree certificates SHOULD send "application/
#    pem-certificate-chain-with-properties" in their Accept header
#    (Section 12.5.1 of [RFC9110]).  ACME servers issuing Merkle Tree
#    certificates SHOULD then respond with that content type and include
#    trust anchor ID information as described in Section 6 of
#    [I-D.ietf-tls-trust-anchor-ids].  Section 8 decribes the trust anchor
#    ID assignments for standalone and landmark certificates.
# 
#    When processing an order for a Merkle Tree certificate, the ACME
#    server moves the order to the "valid" state once the corresponding
#    entry is sequenced in the issuance log.  The order's certificate URL
#    then serves the standalone certificate, constructed as described in
#    Section 6.2.
# 
#    The standalone certificate response SHOULD additionally carry an
#    alternate URL for the landmark certificate, as described
#    Section 7.4.2 of [RFC8555].  Before the landmark certificate is
#    available, the alternate URL SHOULD return a HTTP 503 (Service
#    Unavailable) response, with a Retry-After header (Section 10.2.3 of
#    [RFC9110]) estimating when the certificate will become available.
#    Once the next landmark is allocated, the ACME server constructs a
#    landmark certificate, as described in Section 6.3 and serves it from
#    the alternate URL.
# 
#    ACME clients supporting Merkle Tree certificates SHOULD support
#    fetching alternate chains.  If an alternate chain returns an HTTP 503
#    with a Retry-After header, as described above, the client SHOULD
#    retry the request at the specified time.

[[spec]]
level = "SHOULD"
quote = '''
When downloading the certificate (Section 7.4.2 of [RFC8555]), ACME
clients supporting Merkle Tree certificates SHOULD send "application/
pem-certificate-chain-with-properties" in their Accept header
(Section 12.5.1 of [RFC9110]).
'''

[[spec]]
level = "SHOULD"
quote = '''
ACME servers issuing Merkle Tree
certificates SHOULD then respond with that content type and include
trust anchor ID information as described in Section 6 of
[I-D.ietf-tls-trust-anchor-ids].
'''

[[spec]]
level = "SHOULD"
quote = '''
The standalone certificate response SHOULD additionally carry an
alternate URL for the landmark certificate, as described
Section 7.4.2 of [RFC8555].
'''

[[spec]]
level = "SHOULD"
quote = '''
Before the landmark certificate is
available, the alternate URL SHOULD return a HTTP 503 (Service
Unavailable) response, with a Retry-After header (Section 10.2.3 of
[RFC9110]) estimating when the certificate will become available.
'''

[[spec]]
level = "SHOULD"
quote = '''
ACME clients supporting Merkle Tree certificates SHOULD support
fetching alternate chains.
'''

[[spec]]
level = "SHOULD"
quote = '''
If an alternate chain returns an HTTP 503
with a Retry-After header, as described above, the client SHOULD
retry the request at the specified time.
'''

