target = "draft-ietf-plants-merkle-tree-certs.txt#section-5.5"

# Certification Authority Cosigners
#
#    A _CA cosigner_ is a cosigner (Section 5.4) that certifies the
#    contents of a log.
# 
#    When a CA cosigner signs a subtree, it makes the additional statement
#    that it has certified each entry in the subtree.  For example, a
#    domain-validating CA states that it has performed domain validation
#    for each entry, at some time consistent with the entry's validity
#    dates.  CAs are held responsible for every entry in every subtree
#    they sign.  Proving an entry is included (Section 4.3) in a CA-signed
#    subtree is sufficient to prove the CA certified it.
# 
#    What it means to certify an entry depends on the entry type:
# 
#    *  To certify an entry of type null_entry is a no-op.  A CA MAY
#       freely certify null_entry without being held responsible for any
#       validation.
# 
#    *  To certify an entry of type tbs_cert_entry is to certify the
#       TBSCertificateLogEntry, as defined in Section 5.3.
# 
#    Entries are extensible.  Future documents MAY define type values and
#    what it means to certify them.  A CA MUST NOT sign a subtree if it
#    contains an entry with type that it does not recognize.  Doing so
#    would certify that the CA has validated the information in some not-
#    yet-defined entry format.  Section 12.5 further discusses security
#    implications of new formats.
# 
#    A CA operator MAY operate multiple CA cosigners that all certify the
#    same log in parallel.  This may be useful when, e.g., rotating CA
#    keys.  In this case, each CA instance MUST have a distinct name.  The
#    CA operator's ACME server can return all CA cosignatures together in
#    a single certificate, with the application protocol selecting the
#    cosignatures to use.  Section 8 describes how this is done in TLS
#    [RFC8446].
# 
#    If the CA operator additionally operates a traditional X.509 CA, that
#    CA key MUST be distinct from any Merkle Tree CA cosigner keys.

[[spec]]
level = "MAY"
quote = '''
A CA MAY
freely certify null_entry without being held responsible for any
validation.
'''

[[spec]]
level = "MAY"
quote = '''
Future documents MAY define type values and
what it means to certify them.
'''

[[spec]]
level = "MUST"
quote = '''
A CA MUST NOT sign a subtree if it
contains an entry with type that it does not recognize.
'''

[[spec]]
level = "MAY"
quote = '''
A CA operator MAY operate multiple CA cosigners that all certify the
same log in parallel.
'''

[[spec]]
level = "MUST"
quote = '''
In this case, each CA instance MUST have a distinct name.
'''

[[spec]]
level = "MUST"
quote = '''
If the CA operator additionally operates a traditional X.509 CA, that
CA key MUST be distinct from any Merkle Tree CA cosigner keys.
'''

