target = "draft-ietf-plants-merkle-tree-certs.txt#section-6.1"

# Certificate Format
#
#    The information is encoded in an X.509 Certificate [RFC5280] as
#    follows:
# 
#    The TBSCertificate's version, issuer, validity, subject,
#    issuerUniqueID, subjectUniqueID, and extensions MUST be equal to the
#    corresponding fields of the TBSCertificateLogEntry.  If any of
#    issuerUniqueID, subjectUniqueID, or extensions is absent in the
#    TBSCertificateLogEntry, the corresponding field MUST be absent in the
#    TBSCertificate.  Per Section 5.3, this means issuer MUST be the
#    issuance log's log ID as a PKIX distinguished name, as described in
#    Section 5.2.
# 
#    The TBSCertificate's serialNumber MUST contain the zero-based index
#    of the TBSCertificateLogEntry in the log.  Section 4.1.2.2 of
#    [RFC5280] forbids zero as a serial number, but Section 5.3 defines a
#    null_entry type for use in entry zero, so the index will be positive.
#    This encoding is intended to avoid implementation errors by having
#    the serial numbers and indices off by one.
# 
#    The TBSCertificate's subjectPublicKeyInfo contains the specified
#    public key.  Its algorithm field MUST match the
#    TBSCertificateLogEntry's subjectPublicKeyAlgorithm.  Its hash MUST
#    match the TBSCertificateLogEntry's subjectPublicKeyInfoHash.
# 
#    The TBSCertificate's signature and the Certificate's
#    signatureAlgorithm MUST contain an AlgorithmIdentifier whose
#    algorithm is id-alg-mtcProof, defined below, and whose parameters is
#    omitted.
# 
#    id-alg-mtcProof OBJECT IDENTIFIER ::= {
#        iso(1) identified-organization(3) dod(6) internet(1) security(5)
#        mechanisms(5) pkix(7) algorithms(6) TBD }
# 
#    For initial experimentation, early implementations of this design
#    will use the OID 1.3.6.1.4.1.44363.47.0 instead of id-alg-mtcProof.
# 
#    The signatureValue contains an MTCProof structure, defined below
#    using the TLS presentation language (Section 3 of [RFC8446]):
# 
#    opaque HashValue[HASH_SIZE];
# 
#    struct {
#        TrustAnchorID cosigner_id;
#        opaque signature<0..2^16-1>;
#    } MTCSignature;
# 
#    struct {
#        uint64 start;
#        uint64 end;
#        HashValue inclusion_proof<0..2^16-1>;
#        MTCSignature signatures<0..2^16-1>;
#    } MTCProof;
# 
#    start and end MUST contain the corresponding parameters of the chosen
#    subtree. inclusion_proof MUST contain a subtree inclusion proof
#    (Section 4.3) for the log entry and the subtree. signatures contains
#    the chosen subtree signatures.  In each signature, cosigner_id
#    contains the cosigner ID (Section 5.4) in its binary representation
#    (Section 3 of [I-D.ietf-tls-trust-anchor-ids]), and signature
#    contains the signature value as described in Section 5.4.1.
# 
#    The MTCProof is encoded into the signatureValue with no additional
#    ASN.1 wrapping.  The most significant bit of the first octet of the
#    signature value SHALL become the first bit of the bit string, and so
#    on through the least significant bit of the last octet of the
#    signature value, which SHALL become the last bit of the bit string.

[[spec]]
level = "MUST"
quote = '''
The TBSCertificate's version, issuer, validity, subject,
issuerUniqueID, subjectUniqueID, and extensions MUST be equal to the
corresponding fields of the TBSCertificateLogEntry.
'''

[[spec]]
level = "MUST"
quote = '''
If any of
issuerUniqueID, subjectUniqueID, or extensions is absent in the
TBSCertificateLogEntry, the corresponding field MUST be absent in the
TBSCertificate.
'''

[[spec]]
level = "MUST"
quote = '''
Per Section 5.3, this means issuer MUST be the
issuance log's log ID as a PKIX distinguished name, as described in
Section 5.2.
'''

[[spec]]
level = "MUST"
quote = '''
The TBSCertificate's serialNumber MUST contain the zero-based index
of the TBSCertificateLogEntry in the log.
'''

[[spec]]
level = "MUST"
quote = '''
Its algorithm field MUST match the
TBSCertificateLogEntry's subjectPublicKeyAlgorithm.
'''

[[spec]]
level = "MUST"
quote = '''
Its hash MUST
match the TBSCertificateLogEntry's subjectPublicKeyInfoHash.
'''

[[spec]]
level = "MUST"
quote = '''
The TBSCertificate's signature and the Certificate's
signatureAlgorithm MUST contain an AlgorithmIdentifier whose
algorithm is id-alg-mtcProof, defined below, and whose parameters is
omitted.
'''

[[spec]]
level = "MUST"
quote = '''
start and end MUST contain the corresponding parameters of the chosen
subtree.
'''

[[spec]]
level = "MUST"
quote = '''
inclusion_proof MUST contain a subtree inclusion proof
(Section 4.3) for the log entry and the subtree.
'''

[[spec]]
level = "MUST"
quote = '''
The most significant bit of the first octet of the
signature value SHALL become the first bit of the bit string, and so
on through the least significant bit of the last octet of the
signature value, which SHALL become the last bit of the bit string.
'''

[[spec]]
level = "MUST"
quote = '''
The most significant bit of the first octet of the
signature value SHALL become the first bit of the bit string, and so
on through the least significant bit of the last octet of the
signature value, which SHALL become the last bit of the bit string.
'''

