target = "draft-ietf-plants-merkle-tree-certs.txt#section-8.1"

# Extensions to Trust Anchor IDs
#
#    [[TODO: Move this into draft-ietf-tls-trust-anchor-ids once the
#    PLANTS WG is further along.  See https://github.com/tlswg/tls-trust-
#    anchor-ids/issues/62]]
# 
#    A TLS deployment may know that all relying parties that accept one
#    trust anchor must additionally accept another trust anchor, or desire
#    identifiers for groups of related trust anchors.  For example, in
#    this document, the relying party will recognize up to max_landmark
#    consecutive landmarks, so the latest landmark can be used to
#    represent the range.
# 
#    Incorporating this knowledge into certificate selection can optimize
#    the ClientHello or CertificateRequest extension.  It is RECOMMENDED
#    that this information be provisioned alongside the certificate, e.g.
#    provided by the CA.  This section extends the CertificatePropertyList
#    structure (Section 6 of [I-D.ietf-tls-trust-anchor-ids]) with the
#    additional_trust_anchor_ranges certificate property to do this:
# 
#    enum {
#        additional_trust_anchor_ranges(1), (2^16-1)
#    } CertificatePropertyType;
# 
#    struct {
#        TrustAnchorID base;
#        uint64 min;
#        uint64 max;
#    } TrustAnchorRange;
# 
#    TrustAnchorRange TrustAnchorRangeList<1..2^16-1>;
# 
#    A trust anchor range r is said to _contain_ a trust anchor ID id, if
#    id, as a relative OID, is the concatenation of r.base and some
#    integer component between min and max, inclusive.
# 
#    The following procedure can be used to perform this check.  It
#    succeeds if r contains id and fails otherwise:
# 
#    1.  Check that r.base does not end in the middle of an OID component.
#        That is, check that the most-significant bit of the last byte of
#        r.base is unset.  If it is set, fail the procedure.
# 
#    2.  Check that r.base is a prefix of id.  If not, fail the procedure.
#        Let rest be id with the r.base prefix removed.
# 
#    3.  Decode rest as a minimally-encoded, big-endian, base-128 OID
#        component as follows:
# 
#        1.  If rest is empty, fail the procedure.
# 
#        2.  If the most-significant bit of the last byte of rest is set,
#            fail the procedure.
# 
#        3.  If the most-significant bit of any other byte of rest is
#            unset, fail the procedure.
# 
#        4.  If the first byte of rest is 0x80, fail the procedure.
# 
#        5.  Set v to zero.  Throughout this procedure, v will be less
#            than 2^64.
# 
#        6.  For each byte b of rest:
# 
#            1.  If v is greater than or equal to 2^57, fail the
#                procedure.
# 
#            2.  Set v to (v << 7) + (b & 127).
# 
#    4.  Check if min <= v <= max.  If this is not true, fail the
#        procedure.  Otherwise, the procedure succeeds.
# 
#    Section 4.2 of [I-D.ietf-tls-trust-anchor-ids] is updated as follows.
#    If the ClientHello or CertificateRequest contains a trust_anchors
#    extension, the authenticating party SHOULD send a certification path
#    such that one of the following is true:
# 
#    *  The certification path's trust anchor ID appears in the relying
#       party's trust_anchors extension, or
# 
#    *  One of the certification path's additional trust anchor ranges
#       contains some ID in the relying party's trust_anchors extension
# 
#    Trust anchor ranges do not impact an authenticating party's list of
#    available trust anchors in EncryptedExtensions (see Section 4.3 of
#    [I-D.ietf-tls-trust-anchor-ids]) or the HTTPS/SVCB record (see
#    Section 5 of [I-D.ietf-tls-trust-anchor-ids]).  Those continue to
#    reference the single trust anchor ID that corresponds to each
#    certificate.
# 
#    In applications that use additional trust anchor ranges, relying
#    parties MAY send a single trust anchor ID to represent all
#    certificates whose trust anchor ranges contain that trust anchor ID.
#    This includes:
# 
#    *  Trust anchors that are sent in response to an EncryptedExtensions
#       or HTTPS/SVCB message from the authenticating party
# 
#    *  Trust anchors that are sent in trust_anchors, independently of the
#       authenticating party

[[spec]]
level = "SHOULD"
quote = '''
It is RECOMMENDED
that this information be provisioned alongside the certificate, e.g.
'''

[[spec]]
level = "SHOULD"
quote = '''
If the ClientHello or CertificateRequest contains a trust_anchors
extension, the authenticating party SHOULD send a certification path
such that one of the following is true:
'''

[[spec]]
level = "MAY"
quote = '''
In applications that use additional trust anchor ranges, relying
parties MAY send a single trust anchor ID to represent all
certificates whose trust anchor ranges contain that trust anchor ID.
'''

