target = "draft-ietf-plants-merkle-tree-certs.txt#section-12.5"

# New Log Entry Types
#
#    MerkleTreeCertEntry (Section 5.3) is extensible and permits protocol
#    extensions to define new formats for the CA to certify.  This means
#    older CAs, cosigners, relying parties, and monitors might interact
#    with new entries:
# 
#    Section 5.3 and Section 5.5 forbid a CA from logging or signing
#    entries that it does not recognize.  A CA cannot faithfully claim to
#    certify information if it does not understand it.  This is analogous
#    to how a correctly-operated X.509 CA can never sign an unrecognized
#    X.509 extension.
# 
#    External cosigners may or may not interact with the unrecognized
#    entries.  [TLOG-MIRROR] and [TLOG-WITNESS] describe cosigners whose
#    roles do not interpret the contents of log entries.  New entry types
#    MAY be added without updating them.  If a cosigner role does
#    interpret a log entry, it MUST define how it interacts with unknown
#    ones.
# 
#    If a relying party trusts an issuance log, but the issuance log
#    contains an unrecognized entry, the entry will not cause it to accept
#    an unexpected certificate.  In Section 7.2, the relying party
#    constructs the MerkleTreeCertEntry that it expects.  The unrecognized
#    entry will have a different type value, so the proof will never
#    succeed, assuming the underlying hash function remains collision-
#    resistant.
# 
#    If a monitor observes an entry with unknown type, it may not be able
#    to determine if it is of interest.  For example, it may be unable to
#    tell whether it covers some relevant DNS name.  Until the monitor is
#    updated to reflect the current state of the PKI, the monitor may be
#    unable to detect all misissued certificates.
# 
#    This situation is analogous to the addition of a new X.509 extension.
#    When relying parties add support for log entry types or new X.509
#    extensions, they SHOULD coordinate with monitors to ensure the
#    transparency ecosystem is able to monitor the new formats.

[[spec]]
level = "MAY"
quote = '''
New entry types
MAY be added without updating them.
'''

[[spec]]
level = "MUST"
quote = '''
If a cosigner role does
interpret a log entry, it MUST define how it interacts with unknown
ones.
'''

[[spec]]
level = "SHOULD"
quote = '''
When relying parties add support for log entry types or new X.509
extensions, they SHOULD coordinate with monitors to ensure the
transparency ecosystem is able to monitor the new formats.
'''

