target = "tlog-tiles.md#checkpoints"

# Checkpoints
#
# The Signed Tree Head MUST be served as a [checkpoint][] at
# 
# 	<prefix>/checkpoint
# 
# with `Content-Type: text/plain; charset=utf-8`.
# 
# This endpoint is mutable, so its headers SHOULD prevent caching beyond a few
# seconds.
# 
# If the log is public, or is interacting in any way with the public witness
# network, the checkpoint MUST carry at least one Ed25519 signature by the log.
# The checkpoint MAY carry additional signatures of other types, by the log or
# otherwise.

[[spec]]
level = "MUST"
quote = '''
The Signed Tree Head MUST be served as a [checkpoint][] at
'''

[[spec]]
level = "SHOULD"
quote = '''
This endpoint is mutable, so its headers SHOULD prevent caching beyond a few
seconds.
'''

[[spec]]
level = "MUST"
quote = '''
If the log is public, or is interacting in any way with the public witness
network, the checkpoint MUST carry at least one Ed25519 signature by the log.
'''

[[spec]]
level = "MAY"
quote = '''
The checkpoint MAY carry additional signatures of other types, by the log or
otherwise.
'''

