target = "tlog-tiles.md#retention-policies"

# Retention Policies
#
# This document defines *how* to prune a log, but not policies around *when* or *if*
# a log may be pruned. Log ecosystems that permit pruning SHOULD define retention
# policies for how long entries must be available. Retention policies MUST only
# permit pruning an entry sometime after it will no longer relevant to the log
# application. Retention policies SHOULD also be set so that there is ample time
# for monitors to stay ahead of the minimum index. For example, a
# [Certificate Transparency][] retention policy might require that entries remain
# accessible for 6 months after certificate expiry.
# 
# Without a policy for when pruning is permitted, logs MUST NOT be pruned. That
# is, the minimum index value MUST be set to zero.
# 
# Log applications that support pruning SHOULD additionally define mechanisms for
# applicable log clients to reject entries below some per-log lower bound. This
# lower bound MUST be set to at least the log's current minimum index and SHOULD
# be periodically updated. It MAY be set higher, based on the entries that remain
# relevant to the log application.
# 
# For example, in [Certificate Transparency][], relying parties that support
# prunable logs would set their minimum index to the first unpruned, unexpired,
# unrevoked log entry at a given time, and periodically update it. This ensures
# that, if a log's minimum index is consistent with the lower bounds of up-to-date
# relying parties, those relying parties won't accept pruned entries even if the
# log violated the retention policy. Monitors can use these lower bounds to
# determine whether pruned entries are safe to disregard. However, unupdated
# relying parties with sufficiently stale lower bounds are dependent on retention
# policies to ensure that all pruned entries have already expired.

[[spec]]
level = "SHOULD"
quote = '''
Log ecosystems that permit pruning SHOULD define retention
policies for how long entries must be available.
'''

[[spec]]
level = "MUST"
quote = '''
Retention policies MUST only
permit pruning an entry sometime after it will no longer relevant to the log
application.
'''

[[spec]]
level = "SHOULD"
quote = '''
Retention policies SHOULD also be set so that there is ample time
for monitors to stay ahead of the minimum index.
'''

[[spec]]
level = "MUST"
quote = '''
Without a policy for when pruning is permitted, logs MUST NOT be pruned.
'''

[[spec]]
level = "MUST"
quote = '''
That
is, the minimum index value MUST be set to zero.
'''

[[spec]]
level = "SHOULD"
quote = '''
Log applications that support pruning SHOULD additionally define mechanisms for
applicable log clients to reject entries below some per-log lower bound.
'''

[[spec]]
level = "MUST"
quote = '''
This
lower bound MUST be set to at least the log's current minimum index and SHOULD
be periodically updated.
'''

[[spec]]
level = "MAY"
quote = '''
It MAY be set higher, based on the entries that remain
relevant to the log application.
'''

