target = "static-ct-api.md#checkpoints"

# Checkpoints
#
# The Signed Tree Head is served as a [checkpoint][] at
# 
#     <monitoring prefix>/checkpoint
# 
# with `Content-Type: text/plain; charset=utf-8`.
# 
# This endpoint is mutable, so its headers SHOULD prevent caching beyond a few seconds.
# 
# The checkpoint body MUST encode the size and Merkle Tree Hash of the latest
# public Signed Tree Head, and the origin line MUST be the submission prefix of
# the log as a schema-less URL with no trailing slashes.
# 
# For example, a log with *submission prefix* `https://rome.ct.example.com/2024h1/`
# will use `rome.ct.example.com/2024h1` as the checkpoint origin line.
# 
# The Signed Tree Head signature and timestamp are encoded as a [note
# signature][]. The key name of the signature line MUST match the checkpoint
# origin line. The key ID MUST be the first four bytes (interpreted in big-endian
# order) of the SHA-256 hash of the following sequence: the key name, a newline
# character (`0x0A`), the signature type identifier byte `0x05`, and the 32-byte
# RFC 6962 `LogID`.
# 
# The signature body MUST be an encoding of the following structure.
# 
# ```
# struct {
# 	uint64 timestamp;
# 	TreeHeadSignature signature;
# } RFC6962NoteSignature;
# ```
# 
# “timestamp” is the `TreeHeadSignature.timestamp` field.
# 
# “signature” is the `TreeHeadSignature` digitally-signed value. (Unfortunately, a
# `TreeHeadSignature` does not cover the log’s identity, so the origin line is
# unauthenticated.)
# 
# A checkpoint signed with this algorithm MUST NOT include any extension lines.
# 
# Note that a RFC 6962 `get-sth` response can be converted to a checkpoint (with
# knowledge of the origin line) and vice-versa without access to the private key.
# 
# Checkpoints MAY include other note signatures by the log using different keys or
# key types, or by third parties (such as witnesses). Clients MUST ignore
# signatures with unknown key names and IDs.

[[spec]]
level = "SHOULD"
quote = '''
This endpoint is mutable, so its headers SHOULD prevent caching beyond a few seconds.
'''

[[spec]]
level = "MUST"
quote = '''
The checkpoint body MUST encode the size and Merkle Tree Hash of the latest
public Signed Tree Head, and the origin line MUST be the submission prefix of
the log as a schema-less URL with no trailing slashes.
'''

[[spec]]
level = "MUST"
quote = '''
The checkpoint body MUST encode the size and Merkle Tree Hash of the latest
public Signed Tree Head, and the origin line MUST be the submission prefix of
the log as a schema-less URL with no trailing slashes.
'''

[[spec]]
level = "MUST"
quote = '''
The key name of the signature line MUST match the checkpoint
origin line.
'''

[[spec]]
level = "MUST"
quote = '''
The key ID MUST be the first four bytes (interpreted in big-endian
order) of the SHA-256 hash of the following sequence: the key name, a newline
character (`0x0A`), the signature type identifier byte `0x05`, and the 32-byte
RFC 6962 `LogID`.
'''

[[spec]]
level = "MUST"
quote = '''
The signature body MUST be an encoding of the following structure.
'''

[[spec]]
level = "MUST"
quote = '''
A checkpoint signed with this algorithm MUST NOT include any extension lines.
'''

[[spec]]
level = "MAY"
quote = '''
Checkpoints MAY include other note signatures by the log using different keys or
key types, or by third parties (such as witnesses).
'''

[[spec]]
level = "MUST"
quote = '''
Clients MUST ignore
signatures with unknown key names and IDs.
'''

