target = "draft-ietf-tls-trust-anchor-ids.txt#section-9.2.3"

# Serving Multiple Certificates
#
#    Trust anchor negotiation reduces compatibility pressures against
#    authenticating parties serving certificates from a less common CA, as
#    they can be served with other certificates.  In some cases, the CA
#    may have been distrusted, but still used to support older relying
#    parties.  As discussed in Section 7 and Section 9.2.2, this
#    capability aids PKI transitions that mitigate security risks to
#    users.
# 
#    Even if the CA is untrustworthy, these certificates do not enable the
#    CA to decrypt or intercept the connection.  If a certificate asserts
#    the correct information about the authenticating party, notably the
#    correct public key, the authenticating party can safely present it.
#    Issuing a certificate for the authenticating party's public key does
#    not grant the CA access to the corresponding private key.
#    Conversely, if the attacker already has access to the authenticating
#    party's private key, they do not need to be in control of a CA to
#    intercept a connection.
# 
#    Rather, it is the relying party's choice of trusted CAs that
#    determines susceptibility to interception.  If the relying party
#    trusts a misbehaving or attacker-controlled CA, the attacker can
#    intercept the connection with a public key certified by that CA,
#    regardless of which CA is used by the intended authenticating party.
#    Conversely, if the relying party does not trust the attacker's CA,
#    the attacker cannot successfully intercept the connection using a
#    public key certified by this CA.
# 
#    Choosing trusted CAs is a complex, security-critical process, the
#    full considerations of which are outside the scope of this document.
#    Relying parties thus SHOULD NOT interpret the authenticating party's
#    choice of CA as an endorsement of the CA.  Trusting a CA means
#    trusting _all_ certificates issued by that CA, so it is not enough to
#    observe correct certificates from an authenticating party.  An
#    untrustworthy CA may sign one correct certificate, but also sign
#    incorrect certificates, possibly in the future, that can attack the
#    relying party.

[[spec]]
level = "SHOULD"
quote = '''
Relying parties thus SHOULD NOT interpret the authenticating party's
choice of CA as an endorsement of the CA.
'''

