target = "draft-ietf-tls-trust-anchor-ids.txt#section-3.1"

# Relying Party Configuration
#
#    Relying parties are configured with one or more supported trust
#    anchors.  Each trust anchor that participates in this protocol must
#    have an associated trust anchor ID.
# 
#    When trust anchors are represented as X.509 certificates, the X.509
#    trust anchor ID extension MAY be used to carry this ID.  The trust
#    anchor ID extension has an extnID of id-pe-trustAnchorID and an
#    extnValue containing a DER-encoded TrustAnchorID structure, defined
#    below.  The TrustAnchorID is the trust anchor ID's ASN.1
#    representation, described in Section 3.  This extension MUST be non-
#    critical.
# 
#    id-pe-trustAnchorID OBJECT IDENTIFIER ::=
#        { iso(1) identified-organization(3) dod(6) internet(1)
#          security(5) mechanisms(5) pkix(7) id-pe(1) TBD }
# 
#    TrustAnchorID ::= RELATIVE-OID
# 
#    Relying parties MAY instead or additionally configure trust anchor
#    IDs via some application-specific out-of-band information.
# 
#    Relying parties MAY support trust anchors without associated trust
#    anchor IDs, but such trust anchors will not participate in this
#    protocol.  Those trust anchors MAY participate in other trust anchor
#    negotiation protocols, such as the certificate_authorities extension.

[[spec]]
level = "MAY"
quote = '''
When trust anchors are represented as X.509 certificates, the X.509
trust anchor ID extension MAY be used to carry this ID.
'''

[[spec]]
level = "MUST"
quote = '''
This extension MUST be non-
critical.
'''

[[spec]]
level = "MAY"
quote = '''
Relying parties MAY instead or additionally configure trust anchor
IDs via some application-specific out-of-band information.
'''

[[spec]]
level = "MAY"
quote = '''
Relying parties MAY support trust anchors without associated trust
anchor IDs, but such trust anchors will not participate in this
protocol.
'''

[[spec]]
level = "MAY"
quote = '''
Those trust anchors MAY participate in other trust anchor
negotiation protocols, such as the certificate_authorities extension.
'''

