target = "draft-ietf-tls-trust-anchor-ids.txt#section-6.1"

# Media Type
#
#    A certification path with its associated CertificatePropertyList may
#    be represented in a PEM [RFC7468] structure in a file of type
#    "application/pem-certificate-chain-with-properties".  Files of this
#    type MUST use the strict encoding and MUST NOT include explanatory
#    text.  The ABNF [RFC5234] for this format is as follows, where
#    "stricttextualmsg" and "eol" are as defined in Section 3 of
#    [RFC7468]:
# 
#    certchainwithproperties = stricttextualmsg eol stricttextualmsg
#                              *(eol stricttextualmsg)
# 
#    The first element MUST be the encoded CertificatePropertyList.  The
#    second element MUST be an end-entity certificate.  Each following
#    certificate MUST directly certify the one preceding it.  The
#    certificate representing the trust anchor MUST be omitted from the
#    path.
# 
#    CertificatePropertyLists are encoded using the "CERTIFICATE
#    PROPERTIES" label.  The encoded data is a serialized
#    CertificatePropertyList, defined in Section 6.
# 
#    Certificates are encoded as in Section 5.1 of [RFC7468], except DER
#    [X690] MUST be used.
# 
#    The following is an example file with a certification path containing
#    an end-entity certificate and an intermediate certificate.
# 
#    -----BEGIN CERTIFICATE PROPERTIES-----
#    TODO fill in an example
#    -----END CERTIFICATE PROPERTIES-----
#    -----BEGIN CERTIFICATE-----
#    TODO fill in an example
#    -----END CERTIFICATE-----
#    -----BEGIN CERTIFICATE-----
#    TODO fill in an example
#    -----END CERTIFICATE-----
# 
#    The IANA registration for this media type is described in
#    Section 10.2.

[[spec]]
level = "MUST"
quote = '''
Files of this
type MUST use the strict encoding and MUST NOT include explanatory
text.
'''

[[spec]]
level = "MUST"
quote = '''
Files of this
type MUST use the strict encoding and MUST NOT include explanatory
text.
'''

[[spec]]
level = "MUST"
quote = '''
The first element MUST be the encoded CertificatePropertyList.
'''

[[spec]]
level = "MUST"
quote = '''
The
second element MUST be an end-entity certificate.
'''

[[spec]]
level = "MUST"
quote = '''
Each following
certificate MUST directly certify the one preceding it.
'''

[[spec]]
level = "MUST"
quote = '''
The
certificate representing the trust anchor MUST be omitted from the
path.
'''

[[spec]]
level = "MUST"
quote = '''
Certificates are encoded as in Section 5.1 of [RFC7468], except DER
[X690] MUST be used.
'''

