target = "draft-ietf-tls-trust-anchor-ids.txt#section-5.1"

# Syntax
#
#    The tls-trust-anchors parameter contains an ordered list of one or
#    more trust anchor IDs, in server preference order.
# 
#    The presentation value of the SvcParamValue is a non-empty comma-
#    separated list (Appendix A.1 of [RFC9460]).  Each element of the list
#    is a trust anchor ID in the ASCII representation defined in
#    Section 3.  Any other value is a syntax error.  To enable simpler
#    parsing, this SvcParam MUST NOT contain escape sequences.
# 
#    The wire format of the SvcParamValue is determined by prefixing each
#    trust anchor ID with its length as a single octet, then concatenating
#    each of these length-value pairs to form the SvcParamValue.  These
#    pairs MUST exactly fill the SvcParamValue; otherwise, the
#    SvcParamValue is malformed.
# 
#    For example, if a TLS server has three available certification paths
#    issued by 32473.1, 32473.2.1, and 32473.2.2, respectively, the DNS
#    record in presentation syntax may be:
# 
#    example.net.  7200  IN SVCB 3 server.example.net. (
#        tls-trust-anchors=32473.1,32473.2.1,32473.2.2 )
# 
#    The wire format of the SvcParamValue would be the 17 octets below.
#    In the example, the octets comprising each trust anchor ID are placed
#    on separate lines for clarity
# 
#    0x04, 0x81, 0xfd, 0x59, 0x01,
#    0x05, 0x81, 0xfd, 0x59, 0x02, 0x01,
#    0x05, 0x81, 0xfd, 0x59, 0x02, 0x02,

[[spec]]
level = "MUST"
quote = '''
To enable simpler
parsing, this SvcParam MUST NOT contain escape sequences.
'''

[[spec]]
level = "MUST"
quote = '''
These
pairs MUST exactly fill the SvcParamValue; otherwise, the
SvcParamValue is malformed.
'''

