target = "draft-ietf-tls-trust-anchor-ids.txt#section-4.2"

# Certificate Selection
#
#    A trust_anchors extension in the ClientHello or CertificateRequest is
#    processed similarly to the certificate_authorities extension.  The
#    relying party indicates some set of supported trust anchors in the
#    ClientHello or CertificateRequest trust_anchors extension.  The
#    authenticating party then selects a certificate from its candidate
#    certification paths (see Section 3.2), as described in
#    Section 4.4.2.2 of [RFC8446] and Section 4.4.2.3 of [RFC8446].  This
#    process is extended as follows:
# 
#    If the ClientHello or CertificateRequest contains a trust_anchors
#    extension, the authenticating party SHOULD send a certification path
#    whose trust anchor ID appears in the relying party's trust_anchors
#    extension.
# 
#    If the ClientHello or CertificateRequest contains both trust_anchors
#    and certificate_authorities, certification paths that satisfy either
#    extension's criteria may be used.  This additionally applies to
#    future extensions which play a similar role.
# 
#    If no certification paths satisfy either extension, the
#    authenticating party MAY return a handshake_failure alert, or choose
#    among fallback certification paths without considering trust_anchors
#    or certification_authorities.  See Section 4.3 for additional
#    guidance on selecting a fallback when the ClientHello contains
#    trust_anchors.
# 
#    Sending a fallback allows the authenticating party to retain support
#    for relying parties that do not implement any form of trust anchor
#    negotiation.  In this case, the authenticating party must find a
#    sufficiently ubiquitous trust anchor, if one exists.  However, only
#    those relying parties need to be considered in this ubiquity
#    determination.  Updated relying parties may continue to evolve
#    without restricting fallback certificate selection.
# 
#    If the authenticating party sends a certification path that matches
#    the relying party's trust_anchors extension, as described in
#    Section 4.2, the authenticating party MUST send an empty
#    trust_anchors extension in the first CertificateEntry of the
#    Certificate message.  In this case, the certificate_list flexibility
#    described in Section 4.4.2 of [RFC8446] no longer applies.  The
#    certificate_list MUST contain a complete certification path, issued
#    by the matching trust anchor, correctly ordered and with no
#    extraneous certificates.  That is, each certificate MUST certify the
#    one immediately preceding it, and the trust anchor MUST certify the
#    final certificate.  The authenticating party MUST NOT send the
#    trust_anchors extension in the Certificate message in other
#    situations.
# 
#    If a relying party receives this extension in the Certificate
#    message, it MAY choose to disable path building [RFC4158] and
#    validate the peer's certificate list as pre-built certification path.
#    Doing so avoids the unpredictable behavior of path-building, and
#    helps ensure CAs and authenticating parties do not inadvertently
#    provision incorrect paths.

[[spec]]
level = "SHOULD"
quote = '''
If the ClientHello or CertificateRequest contains a trust_anchors
extension, the authenticating party SHOULD send a certification path
whose trust anchor ID appears in the relying party's trust_anchors
extension.
'''

[[spec]]
level = "MAY"
quote = '''
If no certification paths satisfy either extension, the
authenticating party MAY return a handshake_failure alert, or choose
among fallback certification paths without considering trust_anchors
or certification_authorities.
'''

[[spec]]
level = "MUST"
quote = '''
If the authenticating party sends a certification path that matches
the relying party's trust_anchors extension, as described in
Section 4.2, the authenticating party MUST send an empty
trust_anchors extension in the first CertificateEntry of the
Certificate message.
'''

[[spec]]
level = "MUST"
quote = '''
The
certificate_list MUST contain a complete certification path, issued
by the matching trust anchor, correctly ordered and with no
extraneous certificates.
'''

[[spec]]
level = "MUST"
quote = '''
That is, each certificate MUST certify the
one immediately preceding it, and the trust anchor MUST certify the
final certificate.
'''

[[spec]]
level = "MUST"
quote = '''
That is, each certificate MUST certify the
one immediately preceding it, and the trust anchor MUST certify the
final certificate.
'''

[[spec]]
level = "MUST"
quote = '''
The authenticating party MUST NOT send the
trust_anchors extension in the Certificate message in other
situations.
'''

[[spec]]
level = "MAY"
quote = '''
If a relying party receives this extension in the Certificate
message, it MAY choose to disable path building [RFC4158] and
validate the peer's certificate list as pre-built certification path.
'''

